#ifndef THORLABSTDC001PLUGIN_GLOBAL_H
#define THORLABSTDC001PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef THORLABSTDC001PLUGIN_LIB
# define THORLABSTDC001PLUGIN_EXPORT Q_DECL_EXPORT
#else
# define THORLABSTDC001PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // THORLABSTDC001PLUGIN_GLOBAL_H
