#ifndef THORLABSKINESISPLUGIN_GLOBAL_H
#define THORLABSKINESISPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef THORLABSKINESISPLUGIN_LIB
# define THORLABSKINESISPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define THORLABSKINESISPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // THORLABSKINESISPLUGIN_GLOBAL_H
